### ISSUE TITLE
Integrate devon4j fork

### ISSUE THREAD

**Issue by maybeec** [devonfw-forge/antora-docs-evaluation#3]
Integrate the devon4j fork https://github.com/devonfw-forge/devon4j and track precisely what needs to be adapted on documentation to match the requirements of antora.

Outcome should be integrated docs on gh-pages of this repository.

**Comment by Bene90** [comment]
Still open: linking issue.

**Comment by rvicaria** [comment]
https://github.com/rafaelvicariabarker/antora-docs-evaluation/tree/devon4jFork
