### ISSUE TITLE
Integrate Antora docs to devonfw website

### ISSUE THREAD

**Issue by maybeec** [devonfw-forge/antora-docs-evaluation#4]
Integrate the antora docs into the devonfw.com website by adapting the [fork of devonfw website](https://github.com/devonfw-forge/devonfw.github.io) and deploy it to gh-pages of the fork to make it visuable.

**Comment by Bene90** [comment]
- All repos are working locally.
- Two repos (cicdgen, cobigen) are integrate already to the devonfw.com website.
