### ISSUE TITLE
Find a concept on versioning

### ISSUE THREAD

**Issue by maybeec** [devonfw-forge/antora-docs-evaluation#5]
Currently, we are integrating all modules of documentation by the [wiki links](https://github.com/devonfw/devonfw-guide). Wikis don't have any tags inside the repository. Antora (as far as of my understanding) is basing its documentation versioning on the basis of git tags. So there should be different solutions evaluated to not loose this information like directly linking the repositories or similar solutions.

**Comment by Bene90** [comment]
Documentation can be found here:
https://github.com/devonfw-forge/antora-docs-evaluation/pull/15/files
